title: Abdul M. Bhuiya
logo: /assets/AMB headshot circle.png
description: PhD Candidate
Bioengineering
UC Berkeley-UCSF
#show_downloads: true
theme: jekyll-theme-minimal

# Override styles with custom CSS
#include:
#  - assets
